# Generated by Django 5.1.7 on 2025-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(default='ABC5BDEF', editable=False, max_length=20, unique=True),
        ),
    ]
